### ISSUE TITLE
add "what Thoth knows about you project" teaser feature

### ISSUE THREAD

**Issue by goern** [AICoE/meteor#92]
As a User of the Meteor Web Site,
I want to check a box,
so that a Pull Request is created on the repository I submitted,
and so that the PR give interesting insights on my project.

**Acceptance Criteria**
- [ ] checkout is visible on UI
- [ ] PR is created on user's repository
- [ ] metrics about 'checked boxes', 'created PR', 'accepted PR' is visible in a dashboard

**Comment by durandom** [comment]
This should be "just another tekton pipeline" for the controller. 
I.e. it'll trigger a pipeline that creates a PR as implemented in https://github.com/thoth-station/core/issues/314

Maybe this is an opportunity to refactor the pipeline management in the operator, so that it reuses as mucho code as possible. 

I.e. suppose we add `thoth_pr` to the CR now:

```yaml
apiVersion: meteor.operate-first.cloud/v1alpha1
kind: Meteor
metadata:
  name: demo
spec:
  url: github.com/aicoe-aiops/meteor-demo
  ref: main
  ttl: 100000 # Time to live in seconds, defaults to 24h
  thoth_pr: true 
```

We should only "configure" a mapping of `thoth_pr` to a pipeline that can handle the request. I.e. in the future we can extend the controller to handle new pipelines without changing the pipeline managing code.

**Comment by goern** [comment]
I wonder about the 'configuration' here. As I understand the operator pattern, it is the controller's responsibility, to make sure, that `thoth_pr` will always be in state `true`, so we need to have a bit of logic in the controller, to reconcile a TektonPipelineRun until it yields `true`. Which pipeline to be used, and what parameters, to create the TektonPipelineRun, is hardcoded within the controller. Same for the reconciliation logic. 
I don't know if it is a good practice to have a ConfigMap for the controller, so that we can assign whatever Tekton Pipeline should be executed if a given attribute is set/present on the CR object.

**Comment by tumido** [comment]
So.. I think there are 2 areas in which we want to extend the CRD. This may be a too broad answer to your issue but I think it's necessary to outline it anyways:

1. Let's have a secondary CRD called `Shower` that will deploy the shower web UI and control it for us.
2. `Shower` CRD will also host `meteorDefaults` which will be sourced/merged into each `Meteor` if not specified otherwise (in the `Meteor` itself). (Similar to what Argo Worflow does with a configmap and `workflowDefaults`.) This will allow us to specify global behavior like push to quay or workspace allocations:
```yaml
apiVersion: meteor.operate-first.cloud/v1alpha1
kind: Shower
metadata:
  name: default
spec:
   meteorDefaults:
     workspaces:
       - name: data  # Defines the space used by the pipelines to do work on repositories during pipeline runtime
         volumeClaimTemplate:
           spec:
             accessMode:
               - "ReadWriteOnce"
             resources:
               requests:
                 storage: 500Mi
        - name: quay  # May be pipeline specific and can pass credentials or other things to individual pipelines, like quay credentials
          secret:
            secretName: my-secret
```
3. The `Meteor` resource would be enhanced with a `pipelines` property, that can specify which pipelines should be run. This may be initially specified via UI (checkboxes or what not)
```
apiVersion: meteor.operate-first.cloud/v1alpha1
kind: Meteor
metadata:
  name: demo
spec:
  url: github.com/aicoe-aiops/meteor-demo
  ref: main
  ttl: 100000
  pipelines:
    - jupyterhub
    - jupyterlab
    - something
    - else
  workspaces:  # either defined manually or sourced from Shower
````

3. Now, the operator would use this `pipelines` spec and submits given pipelines
4. Additionally, instead of defining these `pipelines` manually when creating the `Meteor` resource, we can default to a new (to be created) analyze/discovery pipeline. This special pipeline would analyze the repo and figure out which scenarios this  particular repository supports. The operator will then collect outputs from this pipeline and reconcile it back to the `pipelines` list. This will trigger another round of reconcile - making the operator to trigger these newly added pipelines.

That way we can achieve dynamic pipeline provisioning/creation and also all the logic will be stored in Tekton Pipelines:
- discovery pipeline will determine what other pipelines should be triggered for a Meteor on the fly
- all credentials can be supplied to the Meteor via defaults

Future extensions of this can contain things like allowing to blacklist pipelines via the `Shower` resource - for all `Meteors` submitted via that particular `Shower` etc.
